<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>core</string>
	</array>
	<key>name</key>
	<string>coreLanguage</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embeddedCCode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#resetTask</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#taskDef</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#idleTask</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>asyncCall</key>
		<dict>
			<key>begin</key>
			<string>(async) ((after) (\d+(s|ms|us)) )?((before) (\d+(s|ms|us)) )?(?:([A-Za-z_][0-9A-Za-z_]*))\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.core</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.core</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.time.core</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.time.core</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\);</string>
			<key>name</key>
			<string>asyncCall.core</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign.core</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:\s*)((\/\/).*)</string>
					<key>name</key>
					<string>comment.line.core</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:\s*)(\(\*+?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign.core</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\*+\))</string>
					<key>name</key>
					<string>comment.block.core</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>([\w\s\W]*?)</string>
							<key>name</key>
							<string>comment.line.core</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>embeddedCCode</key>
		<dict>
			<key>begin</key>
			<string>(?:^\s*)(#&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.core</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;#)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.core</string>
				</dict>
			</dict>
			<key>name</key>
			<string>Cembedded.core</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<key>idleTask</key>
		<dict>
			<key>begin</key>
			<string>^\s*(Idle)(?:\s*)\{(?:\s*)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.core</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:\s*)\}(?:\s*)$</string>
			<key>name</key>
			<string>idleTask.core</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embeddedCCode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comm</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#asyncCall</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#syncCall</string>
				</dict>
			</array>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>[^\s}]</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.core</string>
		</dict>
		<key>primitifType</key>
		<dict>
			<key>comment</key>
			<string>primitives types</string>
			<key>match</key>
			<string>\b(int|char|bool|byte|void)\b</string>
			<key>name</key>
			<string>storage.type.core</string>
		</dict>
		<key>resetTask</key>
		<dict>
			<key>begin</key>
			<string>^\s*(Reset)(?:\s*)\{(?:\s*)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.core</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:\s*)\}(?:\s*)$</string>
			<key>name</key>
			<string>resetTask.core</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embeddedCCode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comm</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#asyncCall</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#syncCall</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>match</key>
			<string>(\")(\w*\b)(\")</string>
			<key>name</key>
			<string>string.quoted.single.core</string>
		</dict>
		<key>syncCall</key>
		<dict>
			<key>begin</key>
			<string>(sync) ([A-Za-z_][0-9A-Za-z_]*)\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.core</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.core</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\);</string>
			<key>name</key>
			<string>syncCall.core</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<key>taskDef</key>
		<dict>
			<key>begin</key>
			<string>^\s*(Task)\s+([A-Za-z_][0-9A-Za-z_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.core</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.core</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\{)</string>
			<key>name</key>
			<string>meta.class.task.core</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>comment</key>
					<string>classArgs</string>
					<key>end</key>
					<string>(\)\s*)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\s*</string>
							<key>comment</key>
							<string>type identifiant</string>
							<key>end</key>
							<string>\s+([A-Za-z_][0-9A-Za-z_]*)(\s*, )?</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.function.core</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.core</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.class.parameters.core</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.c</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.core</string>
	<key>uuid</key>
	<string>b78bdd86-88be-4e81-909e-046062712a9a</string>
</dict>
</plist>
